config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'toppages/index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  resources :users do
    member do
      get :likes
    end
  end
  resources :categories
  resources :posts do
    resource :likes, only: %i[create destroy]
    resources :comments
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  belongs_to :post, optional: true
  has_many :posts, dependent: :destroy
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :post
  belongs_to :user

  validates :comment, presence: true, length: { maximum: 255 }
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :post_id, uniqueness: { scope: :user_id }
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable counter_cache: true

  has_many :comments, dependent: :destroy
  has_many :categories
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  belongs_to :user

  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 255 }
  validates :content, presence: true, length: { minimum: 10 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :profile, length: { maximum: 255 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password

  mount_uploader :image, ImageUploader

  has_many :posts
  has_many :comments
  has_many :likes
  has_many :like_posts, through: :likes, source: :post

  def like(post)
    likes.find_or_create_by(post_id: post.id)
  end

  def unlike(post)
    like = likes.find_by(post_id: post.id)
    like.destroy if like
  end

  def like?(post)
    like_posts.include?(post)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend
  include SessionsHelper

  private

  def require_user_logged_in?
    redirect_to login_url unless logged_in?
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    @category.save
  end
end

private

def category_params
  params.require(:category).permit(:name)
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :correct_user, only: [:destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = 'コメントを投稿しました'
      redirect_to post_path(@post)
    else
      flash[:danger] = 'コメント投稿に失敗しました'
      redirect_back(fallback_location: posts_path)
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    flash[:success] = 'コメントを削除しました'
    redirect_to post_path(@post)
  end
end

private

def comment_params
  params.require(:comment).permit(:comment, :image)
end

def correct_user
  @comment = current_user.comments.find_by(id: params[:id])
  unless @comment
    flash[:warning] = 'あなたに権限がありません'
    redirect_back(fallback_location: posts_path)
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  def create
    like = current_user.likes.build(post_id: params[:post_id])
    like.save
    flash[:success] = 'お気に入りを登録しました'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = current_user.likes.find_by(post_id: @post.id)
    @like.destroy
    flash[:success] = 'お気に入り登録を外しました'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :require_user_logged_in?
  before_action :unsuer_correct_user, only: [:destroy]

  def index
    @pagy, @posts = pagy(params[:category_id].present? ? Category.find(params[:category_id]).posts.order(id: :desc) : Post.order(id: :desc))
  end

  def show
    @post = Post.find(params[:id])
    impressionist(@post, nil, unique: [:ip_address])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = '投稿されました'
      redirect_to @post
    else
      flash.now[:danger] = '投稿されませんでした'
      render :new
    end
  end

  def destroy
    @post.destroy
    flash[:success] = '投稿は削除されました'
    redirect_to posts_url
  end
end

private

def post_params
  params.require(:post).permit(:content, :title, :image, :category_id)
end

def unsuer_correct_user
  @post = current_user.posts.find_by(id: params[:id])
  unless @post
    flash[:warning] = 'あなたに権限がありません'
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインしました。'
      redirect_to @user
    else
      flash[:danger] = 'メールアドレスまたはパスワードが正しくありません'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      true
    else
      false
    end
  end
end

app/controllers/toppages_controller.rb
# frozen_string_literal: true

class ToppagesController < ApplicationController
  def index
    if logged_in?
      @post = current_user.posts.build
      @pagy, @posts = pagy(current_user.posts.order(id: :desc))
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :require_user_logged_in?, only: %i[show edit likes]
  before_action :correct_user_page, only: [:edit]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    # @pagy, @posts = pagy(@user.posts.order(id: :desc))
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザー登録しました'
      redirect_to @user
    else
      flash[:danger] = 'ユーザー登録に失敗しました'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def likes
    @user = User.find(params[:id])
    @pagy, @posts = pagy(@user.posts.order(id: :desc))
    @like_posts = @user.like_posts
  end
end

private

def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :profile)
end

def correct_user_page
  @user = User.find(params[:id])
  redirect_to(root_url) unless @user == current_user
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
# frozen_string_literal: true

module ToppagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/categories/index.html.erb
<div>
  <ul>
    <% @categories.each do |category| %>
        <%= category.name %>
    <% end %>
  </ul>
</div>

  <div class="top__items">
    <h1>カテゴリー一覧</h1>
  </div>

  <table class="table table-hover">
    <tbody>
      <% @categories.each do |cate| %>
        <tr>
          <td><%= link_to cate.name, posts_path(category_id: cate.id) %></td>
          <td><%= cate.created_at.to_s(:datetime_jp) %>作成</td>
        </tr>
      <% end %>
    </tbody>
  </table>
 

app/views/comments/_comment.html.erb
<div class="comment-group">
    <div class="comment_group_item ">
        <div class="top_item">
            <% if comment.user.image? %>                                                              
                <%= image_tag comment.user.image.url, class: "rounded-circle", size: "80x80" %>
                 <!--##画像が設定されてない場合-->
            <% else %>
                 <%= image_tag "default.png", size: "80x80" %>
            <% end %>
        </div>
    <div class="comment_box">
        <div class="item_left">
         <p><%= comment.user.name %> : <%= comment.created_at %></p>
            <h5><%= comment.comment %></h5>
        </div>
        <div class="item_rigth">
            <% if logged_in? && current_user.id == comment.user_id %>
                
                <button class="btn" type="button"><%= link_to '削除', [comment.post, comment],class: 'btn btn-outline-danger btn-sm',
                      method: :delete,
                      data: { confirm: "本当に削除してもよろしいですか？" } %></button>
            <% end %>
            
        </div>
    </div>
    </div>
</div>
<Hr>

app/views/comments/_form.html.erb
<%= form_with(model:[ @post, @post.comments.build ], local:true) do |f| %>

    <div class="form-group">
        <p>
            <%= f.label 'コメント (255文字未満)' %>
            <%= f.text_area :comment,class: 'form-control' %>
        </p>
    </div>
    <div class="form_action row">
        <%= f.submit 'コメント投稿',class: 'btn btn-primary' %>
    </div>
    
<% end %>

app/views/likes/_like.html.erb
<% if logged_in? %>
  <% if current_user.like?(post)  %> 
      <%=link_to post_likes_path(post), method: :delete do %>
        <i class="fas fa-heart unlike-btn"></i>
      <% end %>
  <% else %>
      <%=link_to post_likes_path(post), method: :post do %>
        <i class="fas fa-heart like-btn"></i>
      <% end %>
  <% end %>
   <%= post.likes.count %>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: @post)do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>

    <div class="form-group">
        <%= f.label :title, ' タイトル(50文字未満)' %>
        <%= f.text_field :title ,class: 'form-control' %>
    </div>
       
    <div class="form-group">
        <%= f.label :content, ' 内容（10文字以上　255文字未満）' %>
        <%= f.text_area :content ,class: 'form-control' %>
    </div>
    <div class="form-group">
        <p><%= f.label :image, '画像' %>
        <%= f.file_field :image, class: "form-control" %> 
        </p>
    </div>
    <div class="form_input">
        <p> <%= f.label :category_id, 'カテゴリー' %>
        
            <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: '選択してください' }, class: 'form-control'%>
        </p>
    </div>
    <div class="form_action row">
        <%= f.submit '投稿', class: 'btn btn-outline-primary' %>
<% end %>
    </div>

app/views/posts/_posts.html.erb
<div class="top__items">


  <div class="ml-auto boards__linkBox">
    <%= form_with url: posts_path, method: :get, class: 'posts__searchForm' do %>
      <%= select_tag :category_id,
                     options_from_collection_for_select(Category.all, :id, :name, params[:category_id]),
                     {
                       prompt: 'カテゴリーを選択',
                       class: 'form-control boards_select',
                       onchange: 'submit(this.form);'
                     } %>
    <% end %>
  </div>
    
<div class="card">
  <% @posts.each do |post| %>
  
  <div class="card-header">
     <%= link_to post.user.name, user_path(post.user), class: "text-decoration-none" %> <span class="text-muted">投稿日時 <%= post.created_at %></span>
  </div>
  
  <div class="card-body d-flex">
   <span><%= image_tag post.image.url, size: "150x150" if post.image? %></span>
   <h5 class="card-title text-center">タイトル：<%= link_to post.title, post %></h5>
   <p class="card-text"></p>
  
 </div>
  <div class="post_bottom_box">
  <div class="raw_left">
   <p class="like_count"><%= render "likes/like", post: post %></p>
    <p class="comment_count"><i class="far fa-comment-dots"></i> <%= post.comments.count %></p>
     <p class="view_count"><i class="far fa-eye"></i><%= post.impressions_count %> </p>
   </div>
   <div class="raw_right">
    <% if logged_in? && current_user.id == post.user_id %>
    <%= link_to '削除', post_path(post.id), class: "btn btn-outline-danger", method: :delete, data: { confirm: '本当にいいですか?' } %>
    <% end %>
     </div>
     </div>
   <% end %>
   
</div>

app/views/posts/index.html.erb
<div class="top__items">
    <h1>投稿一覧</h1>
    <%= render "posts/posts", posts: @posts %>
</div>

<div>
     <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/posts/new.html.erb
<h1>新規投稿ページ</h1>

<%= render "posts/form" %>

app/views/posts/show.html.erb
<h1 class="text-center">投稿詳細ページ</h1>
  <%= link_to '一覧戻る', posts_path, class: 'btn btn-outline-secondary' %>
<Hr>

<h4>タイトル：<%= @post.title %></h4>
<p><%= image_tag @post.image.url, size: "150x150" if @post.image? %></p>
<p><%= @post.user.name %> : <%= @post.created_at %></p>
<h5>内容：<%= @post.content %></h5>

  <p class="comment_count"><i class="far fa-comment-dots"></i> <%= @post.comments.length %>件のコメント数</p>
  
  <div class="comment_list">
  <Hr>
  <p>
  <%= render @post.comments %>
  </p>
  
</div> 

<h2>コメント投稿</h2>
<%= render "comments/form" %>

app/views/toppages/index.html.erb
<% if logged_in? %>
<p>ログイン完了ユーザ<%= current_user.name %></p>
 <div class="row">
    <div class="col-sm-8">
      <%= render 'posts/posts', posts: @posts %>
    </div>
  </div>
<% else %>
  <div class="main">
    <h1 class="masthead-heading text-uppercase mb-0">French Bulldog Posts</h1>
    <%= image_tag 'topimage.jpg', width: '100%', height: '80%'%>
    <p2>I don't have time to worry about who doesn't like me.   I'm too busy loving the people who love me.</p2><i class="fas fa-heart"></i>
    <div class="p-3 p-sm-5 my-4 rounded" >
      <div class="text-center text-brack">
      
      <h3>可愛いけど飼うのが大変だったりする<br>フレンチブルドッグに関する様々な情報をみんなで共有しよう</h3>
      
      <p><%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %></p>
      </div>
  <% end %>
    </div>
  </div>

app/views/users/edit.html.erb
<h1><%= @user.name %> 編集ページ</h1>
 
 
    <%= form_with(model: @user) do |f| %>
     <%= render 'layouts/error_messages', model: f.object %>
      <% if @user.image? %>
        <%= image_tag @user.image.url, class: "rounded-circle", size: "150x150" %>
      <% else %>
        <%= image_tag "default.png", size: "150x150" %>
      <% end %>
      <div class="form-group">
        <%= f.label :profile, 'プロフィール（255文字未満）' %>
        <%= f.text_area :profile, :maxlength => "255", :size => "80x5",  class: 'form-control'  %>
      </div>
      <div>
        <%= f.file_field :image %>
        <%= f.submit 'プロフィール編集を完了する', class: 'btn btn-primary' %>
      </div>
    <% end %>

  <%= link_to '投稿一覧', posts_path, class: 'btn btn-outline-secondary' %>

app/views/users/likes.html.erb
<h1>お気に入り</h1>

  <div class="card">
    <div class="card-header">
      <h3 class="card-title"><%= @user.name %></h3>
  </div>
  <div class="card-body">
    <p>お気に入り一覧</p>
      
      <% @like_posts.each do |post| %>
        <hr>
        <% if logged_in? %>
          <% if current_user.like?(post)  %> 
            <%=link_to post_likes_path(post), method: :delete do %>
            　<i class="fas fa-heart unlike-btn"></i>
          　<% end %>
          <% else %>
            <%=link_to post_likes_path(post), method: :post do %>
            　<i class="fas fa-heart like-btn"></i>
          　<% end %>
          <% end %>
        <% end %>
        <p>お気に入り投稿内容: <%= post.user.name %> : <%=link_to post.content, post_path(post.id) %></p>
      <% end %>
      
  </div>
  
  </div>
    <%= link_to '一覧戻る', posts_path, class: 'btn btn-outline-secondary' %>
   

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      <div class="mb-3">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password_confirmation, 'パスワード再確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '新規登録', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>

app/views/users/show.html.erb
<div class="card">
  <div class="card-header">
   <h1><%= @user.name %>詳細ページ</h1>
  </div>
  <div class="card-body">
      
    <% if @user.image? %>                                                              
      <%= image_tag @user.image.url, class: "rounded-circle", size: "150x150" %>
    <!--##画像が設定されてない場合-->
    <% else %>
      <%= image_tag "default.png", size: "150x150" %>
    <% end %>

    
    <h5 class="card-title">プロフィール</h5>
    <p class="card-text"><%= @user.profile %></p>
    
        <% @posts.each do |post| %>
          <hr>
          <p>投稿内容: <%=link_to post.content, post_path(post.id) %></p>
        <% end %>
  </div>
</div>

  <% if @user.id == current_user.id %>
    <%= link_to '編集ページ',edit_user_path(@user),class: 'btn btn-outline-success' %>
  <% end %>
    <%= link_to '投稿一覧', posts_path, class: 'btn btn-outline-secondary' %>