config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'toppages/index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  resources :users do
    member do
      get :likes
    end
  end
  resources :categories
  resources :posts do
    resource :likes, only: %i[create destroy]
    resources :comments
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  belongs_to :post, optional: true
  has_many :posts, dependent: :destroy
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :post
  belongs_to :user

  validates :comment, presence: true, length: { maximum: 255 }
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :post_id, uniqueness: { scope: :user_id }
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable counter_cache: true

  has_many :comments, dependent: :destroy
  has_many :categories
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  belongs_to :user

  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 255 }
  validates :content, presence: true, length: { minimum: 10 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :profile, length: { maximum: 255 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password

  mount_uploader :image, ImageUploader

  has_many :posts
  has_many :comments
  has_many :likes
  has_many :like_posts, through: :likes, source: :post

  def like(post)
    likes.find_or_create_by(post_id: post.id)
  end

  def unlike(post)
    like = likes.find_by(post_id: post.id)
    like.destroy if like
  end

  def like?(post)
    like_posts.include?(post)
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    @category.save
  end
end

private

def category_params
  params.require(:category).permit(:name)
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :correct_user, only: [:destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = 'コメントを投稿しました'
      redirect_to post_path(@post)
    else
      flash[:danger] = 'コメント投稿に失敗しました'
      redirect_back(fallback_location: posts_path)
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    flash[:success] = 'コメントを削除しました'
    redirect_to post_path(@post)
  end
end

private

def comment_params
  params.require(:comment).permit(:comment, :image)
end

def correct_user
  @comment = current_user.comments.find_by(id: params[:id])
  unless @comment
    flash[:warning] = 'あなたに権限がありません'
    redirect_back(fallback_location: posts_path)
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  def create
    like = current_user.likes.build(post_id: params[:post_id])
    like.save
    flash[:success] = 'お気に入りを登録しました'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = current_user.likes.find_by(post_id: @post.id)
    @like.destroy
    flash[:success] = 'お気に入り登録を外しました'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :require_user_logged_in?
  before_action :unsuer_correct_user, only: [:destroy]

  def index
    @pagy, @posts = pagy(params[:category_id].present? ? Category.find(params[:category_id]).posts.order(id: :desc) : Post.order(id: :desc))
  end

  def show
    @post = Post.find(params[:id])
    impressionist(@post, nil, unique: [:ip_address])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = '投稿されました'
      redirect_to @post
    else
      flash.now[:danger] = '投稿されませんでした'
      render :new
    end
  end

  def destroy
    @post.destroy
    flash[:success] = '投稿は削除されました'
    redirect_to posts_url
  end
end

private

def post_params
  params.require(:post).permit(:content, :title, :image, :category_id)
end

def unsuer_correct_user
  @post = current_user.posts.find_by(id: params[:id])
  unless @post
    flash[:warning] = 'あなたに権限がありません'
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインしました。'
      redirect_to @user
    else
      flash[:danger] = 'メールアドレスまたはパスワードが正しくありません'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      true
    else
      false
    end
  end
end

app/controllers/toppages_controller.rb
# frozen_string_literal: true

class ToppagesController < ApplicationController
  def index
    if logged_in?
      @post = current_user.posts.build
      @pagy, @posts = pagy(current_user.posts.order(id: :desc))
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :require_user_logged_in?, only: %i[show edit likes]
  before_action :correct_user_page, only: [:edit]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    # @pagy, @posts = pagy(@user.posts.order(id: :desc))
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザー登録しました'
      redirect_to @user
    else
      flash[:danger] = 'ユーザー登録に失敗しました'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def likes
    @user = User.find(params[:id])
    @pagy, @posts = pagy(@user.posts.order(id: :desc))
    @like_posts = @user.like_posts
  end
end

private

def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :profile)
end

def correct_user_page
  @user = User.find(params[:id])
  redirect_to(root_url) unless @user == current_user
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
# frozen_string_literal: true

module ToppagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
    
    <small>
        &copy;French Bulldog Posts |
   
    <% if current_user %>
        <%= link_to 'マイページ', @current_user %>
        <%= link_to 'ログアウト',logout_path, method: :delete %>
    <% else %>
        <%= link_to '新規登録', signup_path %>
        <%= link_to 'ログイン', login_path %>
    <% end %>
    </small>
    
</footer>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">French Bulldog Posts</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <% if logged_in? %>
         <div class="btn-group">
      <ul class="navbar-nav">
        <li class="ms-3"><%= link_to '投稿する', new_post_path, class: 'nav-link' %></li>
      </ul>
      <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.name %></button>
      <ul class="dropdown-menu dropdown-menu-end">
        <li class="dropdown-item"><%= link_to 'プロフィール', user_path(current_user), class: 'nav-link' %></li>
        <li class="dropdown-item"><%= link_to 'お気に入り', likes_user_path(current_user), class: 'nav-link' %></li>
        <li class="dropdown-item"><%= link_to '投稿一覧', posts_path, class: 'nav-link' %></li>
        <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
      </ul>
    </div>
  <% else %>
    <ul class="navbar-nav">
      <li class="nav-item"><%= link_to '新規登録', signup_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
    </ul>
  <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FrenchBulldogPosts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.png') %>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
   
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
   
  </body>
</html>